### ISSUE TITLE
n_fft is too small

### ISSUE THREAD

**Issue by wwerkk** [materialvision/augment_audio_tools#1]
When augmenting a dataset of one-shot samples some of them are very short
in result, running ``augment_audio.py`` throws ```~/.local/lib/python3.9/site-packages/librosa/util/decorators.py:88: UserWarning: n_fft=2048 is too small for input signal of length=2```

Not sure if currently it's simply omitting these frames entirely, is that something I should pay attention to and perhaps pad them beforehand with a short period of silence? Cannot tell how much valid info would these contain anyway...

**Comment by materialvision** [comment]
Hi yes the augment_audio.py do not have all the checks that augment_audio_speed.py has, I kept it there as a different way to augment, but I will remove it from the repo, as it is confusing.

augment_audio_speed.py is the script to use!

**Comment by wwerkk** [comment]
that makes sense, thanks!
closing this issue as ``augment_audio.py`` has been removed
