### ISSUE TITLE
Concatenate error using --add_silence withough --split_stereo

### ISSUE THREAD

**Issue by devstermarts** [materialvision/augment_audio_tools#3]
Hey there, when running the script with --add_silence X but **without** --split_stereo, the following error occurs: 

` File "/.../augment_audio_tools/augment_audio_speed.py", line 85, in <module>
    process_audio_file(input_file, args.output_folder, args.chunk_duration, args.split_stereo, args.add_silence, args.speed_change)
  File "/.../augment_audio_tools/augment_audio_speed.py", line 44, in process_audio_file
    chunk = np.concatenate((chunk, silence))
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)`

**Comment by materialvision** [comment]
Thanks, I tried to push a fix now by mixing stereo to mono if not --split_stereo set.

**Comment by devstermarts** [comment]
Confirmed this works. Thanks for the swift fix :)
